[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "py_sas_studio_custom_steps"
version = "2.2.0"
authors = [
  { name="Sundaresh Sankaran", email="sundaresh.sankaran@gmail.com" },
]
description = "A package containing a Python class and associated methods, along with an MCP server script to create and manipulate SAS Studio Custom Step files."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/SundareshSankaran/py-sas-studio-custom-steps"
Issues = "https://github.com/SundareshSankaran/py-sas-studio-custom-steps/issues"